name: Ahk2Exe v2 scripts
description: Convert AutoHotkey v2 scripts to executables with Ahk2Exe
author: tamo

inputs:
  ahk2exe:
    description: compiler
    required: false
    default: _ahktmp/Ahk2Exe.exe
  base:
    description: binary to embed
    required: false
    default: _ahktmp/AutoHotkey32.exe
  src:
    description: script
    required: false
    default: ""
  opt:
    description: other options for ahk2exe
    required: false
    default: ""
  tmpdir:
    description: folder to download zips in
    required: false
    default: _ahktmp

runs:
  using: composite
  steps:
    - name: Fetch executables
      shell: pwsh
      run: |
        function latesturl ($repo, $type) {
          $cwd = pwd;
          if (!(Test-Path "${{ inputs.tmpdir }}")) {
            mkdir "${{ inputs.tmpdir }}";
          }
          cd "${{ inputs.tmpdir }}";
          curl -H "Accept: application/vnd.github.v3+json" -o _latest.json --no-progress-meter "https://api.github.com/repos/${repo}/releases/latest";
          cat _latest.json | jq -r ('.assets[] | select(.content_type == \"{0}\") | .browser_download_url' -f ${type});
          cd "${cwd}";
        }
        function fetchit ($url, $zip, $file) {
          $cwd = pwd;
          cd "${{ inputs.tmpdir }}";
          curl -LJo "${zip}" "${url}";
          7z x "${zip}";
          cd "${cwd}";
          if (!(Test-Path "${file}")) {
            cp "${{ inputs.tmpdir }}/${file}" "${file}";
          }
        }
        if (Test-Path "${{ inputs.ahk2exe }}") {
          echo "Ahk2Exe is already here";
        } else {
          $A2EURL = latesturl "AutoHotkey/Ahk2Exe" "application/x-zip-compressed";
          fetchit "${A2EURL}" "a2e.zip" "${{ inputs.ahk2exe }}";
        }
        if (Test-Path "${{ inputs.base }}") {
          echo "Base binary is already here";
        } else {
          $AHKURL = latesturl "AutoHotkey/AutoHotkey"  "application/zip";
          fetchit "${AHKURL}" "ahk.zip" "${{ inputs.base }}";
        }
    - name: Build
      if: inputs.src != ''
      shell: pwsh
      run: |
        $a2e = ls "${{ inputs.ahk2exe }}";
        & ${a2e} /base "${{ inputs.base }}" /in "${{ inputs.src }}" ${{ inputs.opt }};
