name: CI

on: [push, workflow_dispatch]

jobs:
  v2:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
        with:
          repository: tamo/RestoreWinPos.ahk

      - name: 32bit and 64bit
        uses: tamo/action-Ahk2Exe@multifile
        with:
          base: AutoHotkey32.exe,AutoHotkey64.exe
          src: RestoreWinPos.ahk

      - run: |
          ls RestoreWinPos32.exe
          ls RestoreWinPos64.exe

      - name: 32bit simplest
        uses: tamo/action-Ahk2Exe@multifile
        with:
          src: RestoreWinPos.ahk

      - run: ls RestoreWinPos.exe

      - run: |
          mkdir src
          cp RestoreWinPos.ahk src/RestoreWinPos-copied.ahk

      - name: 32bit and 64bit with tmpdir
        uses: tamo/action-Ahk2Exe@multifile
        with:
          src: src/RestoreWinPos-copied.ahk
          base: _ahktmp/AutoHotkey32.exe,_ahktmp/AutoHotkey64.exe

      - run: |
          ls src/RestoreWinPos-copied32.exe
          ls src/RestoreWinPos-copied64.exe

  v1:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
        with:
          repository: Lexikos/dbgp
          ref: one

      - name: v1 without downloading Ahk2Exe
        uses: tamo/action-Ahk2Exe@multifile
        with:
          taghead: v1.1.
          base: _ahktmp/AutoHotkeyU32.exe
          ahk2exe: _ahktmp/Compiler/Ahk2Exe.exe

      - name: 32bit Unicode exe base in tmpdir (with included Ahk2Exe)
        uses: tamo/action-Ahk2Exe@multifile
        with:
          src: dbgp_benchmark.ahk
          base: _ahktmp/AutoHotkeyU32.exe
          ahk2exe: _ahktmp/Compiler/Ahk2Exe.exe

      - run: ls dbgp_benchmark.exe

      - name: multiple (download Ahk2Exe here)
        uses: tamo/action-Ahk2Exe@multifile
        with:
          src: dbgp_benchmark.ahk,dbgp_test.ahk
          base: AutoHotkeyA32.exe,AutoHotkeyU32.exe,AutoHotkeyU64.exe

      - run: |
          ls dbgp_benchmarkA32.exe
          ls dbgp_benchmarkU32.exe
          ls dbgp_benchmarkU64.exe
          ls dbgp_testA32.exe
          ls dbgp_testU32.exe
          ls dbgp_testU64.exe

      - run: |
          mkdir src
          cp *.ahk src/

      - name: 64bit Unicode bin base in tmpdir
        uses: tamo/action-Ahk2Exe@multifile
        with:
          src: "src/dbgp_benchmark.ahk,src/dbgp_test.ahk"
          base: "_ahktmp/Compiler/Unicode 64-bit.bin"

      - run: |
          ls src/dbgp_benchmark.exe
          ls src/dbgp_test.exe
